version: '3'

services:
  app:
    image: ttl.sh/test-node-zipofar:3m
    entrypoint: /bin/bash
    command:
      - "-c"
      - "node /app/app/app.js"

x-uffizzi:
  ingress:
    service: app
    port: 8080

  continuous_preview:
    delete_preview_after: 10h
