version: '3'

services:
  app:
    image: ghcr.io/zipofar/test-node:latest1
  redis:
    image: redis:latest1
    
x-uffizzi:
  ingress:
    service: app
    port: 80


  continuous_preview:
    delete_preview_after: 10h
