version: '3'

services:
  app:
    image: ghcr.io/zipofar/test-node:latest
    volumes:
      - db_data:/var/opt/mssql
    
  redis:
    image: redis:latest

volumes:
  db_data:

x-uffizzi:
  ingress:
    service: app
    port: 80


  continuous_preview:
    delete_preview_after: 10h
