version: '3'

services:
  app:
    build:
      context: https://github.com/zipofar/test_node#feature/map-envs
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    command:
      - "-c"
      - "REDIRECT_URL=$$UFFIZZI_URL/home ENDPOINT=$$UFFIZZI_URL/entrypoint node /app/app/app.js"

x-uffizzi:
  ingress:
    service: app
    port: 80

  continuous_preview:
    delete_preview_after: 10h
