apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
spec:
  ports:
  - port: {{ .Values.app_port }}
    protocol: TCP
    targetPort: {{ .Values.app_port }}
  selector:
    app: {{ .Release.Name }}
  sessionAffinity: None
